### ISSUE TITLE
organizar a estrutura de pastas.

### ISSUE THREAD

**Issue by JCDMeira** [luizgalluzzi/Portfolio#2]
Quanto maiores os projetos, maior é a necessidade de organizar as pastas, porque o volume de arquivos aumenta e fica fácil se perder. Além disso alguns sites dependem de uma estrutura para fazer o deploy do projeto, a netlify mesmo recomenda. Então a estrutura que costumo indicar é, criar uma pasta assets, dentro dela crie pastas para css, js, img e qualquer uma mais que forem necessárias. Se tiver dúvidas da pra procurar pelo modelo. Daí é só deixar cada tipo de arquivo na sua respectiva pasta

![Captura de tela de 2022-10-10 21-07-34](https://user-images.githubusercontent.com/65555624/195221011-5421bb8c-300c-496a-a2a6-083258f27dc7.png)

**Comment by luizgalluzzi** [comment]
closed #2

Tentei reorganizar as pastas e os links de do arquivo .css e .img foram perdidos. Mesmo consertando o link. Para os projetos existentes vou manter as pastas do jeito que estão. Para os próximos, vou organizar conforme recomendado.
